import fs from 'node:fs'
import path from 'node:path'

import { ConfigPlugin, withPodfile as withExpoPodfile } from '@expo/config-plugins'

const packageJson = fs.readFileSync(path.join(__dirname, '..', '..', '..', '..', '..', 'package.json'), 'utf8')
const libraryName = JSON.parse(packageJson).name

/**
 * Find the path to the voltra package by resolving from the project root.
 */
function findVoltraPackagePath(projectRoot: string): string {
  // Try to resolve the voltra package.json from the project root
  const possiblePaths = [
    // Standard node_modules location
    path.join(projectRoot, 'node_modules', libraryName),
    // Parent directory (for monorepo/nativeModulesDir setup)
    path.resolve(projectRoot, '..'),
    // Current directory (in case plugin is run from voltra itself)
    projectRoot,
  ]

  for (const p of possiblePaths) {
    const pkgPath = path.join(p, 'package.json')
    if (fs.existsSync(pkgPath)) {
      try {
        const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'))
        if (pkg.name === libraryName) {
          return p
        }
      } catch {
        // Ignore parse errors
      }
    }
  }

  // Fallback to node_modules
  return path.join(projectRoot, 'node_modules', libraryName)
}

/**
 * Generates the Podfile target content for the widget extension.
 */
function getTargetContent(targetName: string, podspecDirPath: string): string {
  return `
# Voltra Widget Extension Target
# DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED BY THE VOLTRA PLUGIN
target '${targetName}' do
  use_frameworks! :linkage => podfile_properties['ios.useFrameworks'].to_sym if podfile_properties['ios.useFrameworks']
  use_frameworks! :linkage => ENV['USE_FRAMEWORKS'].to_sym if ENV['USE_FRAMEWORKS']

  pod 'VoltraWidget', :path => '${podspecDirPath}'
end`
}

export interface ConfigurePodfileProps {
  targetName: string
}

/**
 * Plugin step that adds the Podfile target for the widget extension.
 */
export const configurePodfile: ConfigPlugin<ConfigurePodfileProps> = (config, { targetName }) => {
  return withExpoPodfile(config, (podfile) => {
    // Find voltra package path
    const projectRoot = podfile.modRequest.projectRoot
    const voltraPath = findVoltraPackagePath(projectRoot)
    const iosPath = path.join(voltraPath, 'ios')
    
    // Calculate relative path from ios directory to voltra ios directory
    const iosDir = path.join(projectRoot, 'ios')
    const relativePath = path.relative(iosDir, iosPath)
    
    const targetContent = getTargetContent(targetName, relativePath)

    // Check if target already exists (avoid duplicates)
    const targetMarker = "target '" + targetName + "'"
    if (podfile.modResults.contents.includes(targetMarker)) {
      return podfile
    }

    podfile.modResults.contents = podfile.modResults.contents + '\n' + targetContent
    return podfile
  })
}
