//
//  VoltraWidgetInitialStates.swift
//
//  Auto-generated by setup-widget-extension.sh
//  No widget initial states configured (Live Activity only).
//

import Foundation

public enum VoltraWidgetInitialStates {
  /// Get the bundled initial state JSON for a widget.
  /// Always returns nil since no home screen widgets are configured.
  public static func getInitialState(for widgetId: String) -> Data? {
    return nil
  }
}
