//
//  VoltraWidgetBundle.swift
//
//  Auto-generated by setup-widget-extension.sh
//  This file defines which Voltra widgets are available in your app.
//

import SwiftUI
import WidgetKit
import VoltraWidget  // Import Voltra widgets

@main
struct VoltraWidgetBundle: WidgetBundle {
  var body: some Widget {
    // Live Activity Widget (Dynamic Island + Lock Screen)
    VoltraWidget()
  }
}
